# Generated by Django 5.2.16 on 2026-07-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Local')),
                ('result', models.CharField(blank=True, max_length=150, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Competição',
                'verbose_name_plural': 'Competições',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('attended', models.BooleanField(default=True, verbose_name='Presente')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
                'ordering': ['-date'],
            },
        ),
    ]
