# Generated by Django 5.2.16 on 2026-07-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='attended',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('foi', 'Fui'), ('nao_foi', 'Não fui'), ('desculpa', 'Tive uma desculpa')], default='foi', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
    ]
