# Generated by Django 5.2.16 on 2026-07-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_trainingsession_attended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='location',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='result',
        ),
        migrations.AddField(
            model_name='competition',
            name='club',
            field=models.CharField(blank=True, max_length=150, verbose_name='Clube'),
        ),
        migrations.AddField(
            model_name='competition',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome da competição'),
        ),
        migrations.CreateModel(
            name='SwimResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('50_livre', '50m Livre'), ('100_livre', '100m Livre'), ('200_livre', '200m Livre'), ('400_livre', '400m Livre'), ('50_costas', '50m Costas'), ('100_costas', '100m Costas'), ('50_peito', '50m Peito'), ('100_peito', '100m Peito'), ('50_borboleta', '50m Borboleta'), ('100_borboleta', '100m Borboleta'), ('200_medley', '200m Medley'), ('outro', 'Outra prova')], max_length=20, verbose_name='Prova')),
                ('time_centiseconds', models.PositiveIntegerField(verbose_name='Tempo (centésimos)')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sports.competition', verbose_name='Competição')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['event'],
            },
        ),
    ]
