# Generated by Django 5.2.16 on 2026-07-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_remove_competition_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimresult',
            name='placement',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Colocação'),
        ),
    ]
