# Generated by Django 5.2.16 on 2026-07-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('google', 'Google Agenda'), ('auto', 'Gerado automaticamente')], default='manual', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='Padrão RRULE, ex: FREQ=WEEKLY;BYDAY=TU', max_length=255)),
                ('show_in_upcoming', models.BooleanField(default=True, help_text="Se desmarcado, o evento aparece só no calendário, não em 'próximos eventos'")),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
