# Generated by Django 5.2.16 on 2026-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Repetir evento'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text='Padrão RRULE, ex: FREQ=WEEKLY;BYDAY=TU', max_length=255, verbose_name='Regra de recorrência'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google Agenda'), ('auto', 'Gerado automaticamente')], default='manual', max_length=10, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
