# Generated by Django 5.2.16 on 2026-07-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_key',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
