# Generated by Django 5.2.16 on 2026-07-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído'), ('entregue', 'Entregue')], default='pendente', max_length=10),
        ),
    ]
