# Generated by Django 5.2.16 on 2026-07-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date'], 'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['date'], 'verbose_name': 'Prova', 'verbose_name_plural': 'Provas'},
        ),
        migrations.AlterModelOptions(
            name='studyfile',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='studylog',
            options={'ordering': ['-date'], 'verbose_name': 'Tempo estudado', 'verbose_name_plural': 'Tempos estudados'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Matéria', 'verbose_name_plural': 'Matérias'},
        ),
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome da prova'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(verbose_name='Data de entrega'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído'), ('entregue', 'Entregue')], default='pendente', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='studies.subject', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='studies.subject', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='studyfile',
            name='file',
            field=models.FileField(upload_to='studies/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='studyfile',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='studies.subject', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='studyfile',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='minutes',
            field=models.PositiveIntegerField(verbose_name='Minutos estudados'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='studies.subject', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
