# Generated by Django 5.2.16 on 2026-07-19 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_assignment_options_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='grade',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Trabalho'), ('atividade', 'Atividade'), ('caderno', 'Caderno'), ('outro', 'Outro')], default='prova', max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Nota')),
                ('bimester', models.PositiveSmallIntegerField(choices=[(1, '1º bimestre'), (2, '2º bimestre'), (3, '3º bimestre'), (4, '4º bimestre')], verbose_name='Bimestre')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='studies.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['bimester', 'date'],
            },
        ),
        migrations.CreateModel(
            name='StudyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('falta_estudar', 'Falta estudar'), ('estudado', 'Estudado'), ('revisado', 'Revisado')], default='falta_estudar', max_length=15, verbose_name='Status')),
                ('questions_done', models.BooleanField(default=False, verbose_name='Já resolvi questões desse conteúdo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='studies.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Conteúdo estudado',
                'verbose_name_plural': 'Conteúdos estudados',
                'ordering': ['status', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='StudyFile',
        ),
    ]
