# Generated by Django 5.2.16 on 2026-07-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_remove_exam_grade_grade_studycontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycontent',
            name='questions_done',
            field=models.BooleanField(default=False, verbose_name='Já coloquei as questões no Anki'),
        ),
    ]
