# Generated by Django 5.2.16 on 2026-07-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_alter_studycontent_questions_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcusedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Dia com desculpa',
                'verbose_name_plural': 'Dias com desculpa',
            },
        ),
    ]
