# Generated by Django 5.2.16 on 2026-07-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Registro de creatina',
                'verbose_name_plural': 'Registros de creatina',
                'ordering': ['-date'],
            },
        ),
    ]
